# Generated by Django 5.2.8 on 2026-01-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_name',
            field=models.CharField(choices=[('create-outline', 'Writing/Content (Pen)'), ('code-slash-outline', 'Development (Code)'), ('bar-chart-outline', 'Strategy/Analytics (Chart)'), ('brush-outline', 'Design (Brush)'), ('mic-outline', 'Speaking/Audio (Mic)'), ('people-outline', 'Management (People)'), ('camera-outline', 'Photography (Camera)'), ('videocam-outline', 'Video (Camera)'), ('mail-outline', 'Email/Communication (Mail)')], default='create-outline', help_text='Select an icon for this service', max_length=50),
        ),
    ]
