# Generated by Django 5.2.8 on 2026-01-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('testimonial_text', models.TextField()),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
        ),
    ]
