# Generated by Django 5.2.8 on 2026-01-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_image',
            field=models.CharField(blank=True, help_text='Auto-assigned based on gender', max_length=255, null=True),
        ),
    ]
