# Generated by Django 5.2.8 on 2026-01-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_gender_alter_testimonial_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_date',
            field=models.DateField(blank=True, help_text='Date of testimonial', null=True),
        ),
    ]
