# Generated by Django 5.2.8 on 2026-01-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(help_text='Percentage 0-100')),
                ('category', models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('Tools', 'Tools & DevOps'), ('Other', 'Other')], default='Other', max_length=50)),
                ('icon', models.FileField(blank=True, null=True, upload_to='skills/')),
            ],
        ),
    ]
