# Generated by Django 5.2.8 on 2026-01-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='link',
            field=models.URLField(blank=True, help_text='External link to the full article', null=True),
        ),
    ]
